[package]
name = "mayerror"
version = "0.1.0"
edition = "2021"

[dependencies]
backtrace = "0.3.73"
mayerror-derive = { version = "=0.1.0", path = "derive" }
owo-colors = "4.0.0"

[dev-dependencies]
thiserror = "1.0.62"

[workspace]
members = ["derive"]
