[package]
name = "mayerror"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
owo-colors = "4.0.0"
proc-macro2 = "1.0.85"
quote = "1.0.36"
syn = "2.0.66"

[dev-dependencies]
thiserror = "1.0.61"
