[package]
name = "mayerror"
version = "0.1.0"
edition = "2021"

[dependencies]
owo-colors = "4.0.0"
mayerror-derive = { version = "=0.1.0", path = "derive" }

[dev-dependencies]
thiserror = "1.0.61"

[workspace]
members = ["derive"]
